### ISSUE TITLE
HTTPS Fails to Initialize

### ISSUE THREAD

**Issue by Reahreic** [ritwickdey/vscode-live-server#1599]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

When starting Live Server with HTTPS enabled, the below error is pushed to the developer console, and the server doesn't start. Live Server works correctly with HTTPS disabled.

[Extension Host] Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE    at createSecureContext (_tls_common.js:129:17)    at Object.createSecureContext (c:\Users\4tsbl\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-proxy-agent\out\index.js:360:36)    at Server.setSecureContext (_tls_wrap.js:1321:27)    at Server (_tls_wrap.js:1185:8)    at new Server (https.js:68:14)    at Object.createServer (https.js:92:10)    at Object.LiveServer.start (c:\Users\4tsbl\.vscode\extensions\ritwickdey.liveserver-5.6.1\node_modules\live-server\index.js:268:29)    at Timeout._onTimeout (c:\Users\4tsbl\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\LiveServerHelper.js:9:49)    at listOnTimeout (internal/timers.js:549:17)    at processTimers (internal/timers.js:492:7)

## Expected behavior

Live Server starts  using HTTPS with the defined cert data.

## Environment

```html
Browser:

- [x] Chrome (desktop) version 90
- [x] Firefox version 87
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [x] Edge version 90

For Tooling issues:

- Live Server: 5.6.1
- Platform:  Windows
- Visual Studio Code: 1.55.2
```

**Comment by djryanash** [comment]
It seems no one cares and no one is maintaining this repo anymore. :(

I am having the same issue with SSL/HTTPS.  After generating a Self-Signed Certificate, and stopping and trying to restart the server, it won't start.  It just fails silently.
