### ISSUE TITLE
Live Server Not Working - Copied the below error messages from the DevTools console

### ISSUE THREAD

**Issue by NSM722** [ritwickdey/vscode-live-server#2639]
Sorry, it's not the code from LiveServer, maybe some internal code from vscode. You'll find logs from Developer Console option.  ` (Help -> toogle developer tool -> console)`

_Originally posted by @ritwickdey in https://github.com/ritwickdey/vscode-live-server/issues/2571#issuecomment-1237954202_
----------------------------------------------------------------------
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at Object.readFileSync (node:fs:453:35)
	at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at Helper.getHttpsSetup (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\Helper.js:131:27)
	at Helper.generateParams (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\Helper.js:98:30)
	at AppModel.<anonymous> (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\appModel.js:59:42)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\appModel.js:5:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
mainThreadExtensionService.ts:80 Error: ENOENT: no such file or directory, open
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at Object.readFileSync (node:fs:453:35)
	at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at Helper.getHttpsSetup (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\Helper.js:131:27)
	at Helper.generateParams (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\Helper.js:98:30)
	at AppModel.<anonymous> (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\appModel.js:59:42)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\user\.vscode\extensions\ritwickdey.liveserver-5.7.8\out\src\appModel.js:5:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by NSM722** [comment]
<img width="409" alt="live_server_error" src="https://user-images.githubusercontent.com/83452606/199956270-bee21505-cdf5-499b-b4ac-e92c40356968.png">

**Comment by NSM722** [comment]
<img width="406" alt="live_server_error2" src="https://user-images.githubusercontent.com/83452606/199956523-125203c9-0d49-421c-ae35-15bb551583cf.png">
