### ISSUE TITLE
Activating extension 'ritwickdey.LiveServer' failed: Cannot find module 'connect'.

### ISSUE THREAD

**Issue by mayasky76** [ritwickdey/vscode-live-server#447]
## Current behavior
No Go live button and right clicking on open with live server in context menu not working
Happens on all html files? Used to work fine
Tried uninstalling re-installing, updating ets
Developer tools gives me the below message?

## Environment
Line (               ...): longer than 20000 characters, tokenization skipped.
/C:/Users/isw44/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3264 [Extension Host] debugger listening on port 21672
/C:/Users/isw44/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3343 Activating extension 'ritwickdey.LiveServer' failed: Cannot find module 'connect'.
_logMessageInConsole @ /C:/Users/isw44/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3343
/C:/Users/isw44/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] Activating extension `ritwickdey.LiveServer` failed:  Cannot find module 'connect'
t.log @ /C:/Users/isw44/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:235
/C:/Users/isw44/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] Here is the error stack:  Error: Cannot find module 'connect'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\node_modules\live-server\index.js:11:12)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\node_modules\live-server\index.js:463:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\LiveServerHelper.js:3:20)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\LiveServerHelper.js:37:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\appModel.js:12:28)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\appModel.js:269:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\extension.js:12:20)
	at Object.<anonymous> (C:\Users\isw44\.vscode\extensions\ritwickdey.liveserver-5.6.1\out\src\extension.js:45:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:31:542)
	at c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:717:918
	at E._doActivateExtension (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:718:2)
	at E._activateExtension (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:716:772)
	at E.<anonymous> (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:714:224)
	at Generator.next (<anonymous>)
	at n (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:11:176)
	at new Promise (<anonymous>)
	at n (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:975)
	at Object.actualActivateExtension (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:713:946)
	at p._activateExtension (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:765)
	at define._activateExtensions.i.length.Promise.all.o.map.e (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:449)
	at Array.map (<anonymous>)
	at p._activateExtensions (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:457:437)
	at p.activateByEvent (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:455:375)
	at E._activateByEvent (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:715:434)
	at E._handleEagerExtensions (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:719:365)
	at define._startExtensionHost._readyToRunExtensions.wait.then (c:\Users\isw44\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:722:430)

**Comment by ritwickdey** [comment]
delete live server folder from `C:\Users\isw44.vscode\extensions\ritwickdey.liveserver-5.6.1\`

**Comment by mayasky76** [comment]
Excellent - deleted folder and re-installed and all works now Thanks
