### ISSUE TITLE
LiveServer cannot find module 'statuses'

### ISSUE THREAD

**Issue by julesmqz** [ritwickdey/vscode-live-server#75]
I am having following issue:

```
Here is the error stack:  Error: Cannot find module 'statuses'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\julmarqu\.vscode\extensions\ritwickdey.liveserver-3.2.0\node_modules\finalhandler\index.js:17:16)
	at Object.<anonymous> (C:\Users\julmarqu\.vscode\extensions\ritwickdey.liveserver-3.2.0\node_modules\finalhandler\index.js:249:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
Activating extension `ritwickdey.LiveServer` failed: Cannot find module 'statuses'.
```

I can't compile sass files because of this and don't understand what could be happening. Can you help me? 

Forgot to mention that my VSCode is version 1.20

**Comment by ritwickdey** [comment]
Btw, which version of vscode you're using?

anyway, the error message is  `Cannot find module "statuses"`. This extension is not using any statuses module. It may be internal module of vscode, I'm not sure.

**Comment by ritwickdey** [comment]
An Update! Yep! this extension is using `statuses` package! (Actually, dependency of dependency 😄 )


checkout this location: 
`C:\Users\julmarqu\.vscode\extensions\ritwickdey.liveserver-3.2.0\node_modules`

is there any folder named `statuses` ?

![image](https://user-images.githubusercontent.com/18099464/36040363-37b3e812-0deb-11e8-918a-15d1d45fbf4e.png)

**Comment by julesmqz** [comment]
you are right! I am missing the statuses folder 
![image](https://user-images.githubusercontent.com/2530806/36041284-a4241da4-0d8d-11e8-88a1-c20e430a0386.png)
Do you know how can I install it?

**Comment by ritwickdey** [comment]
This should come while you're installing the extension.

Did you try to reinstall process?

**Comment by julesmqz** [comment]
What I did was remove those folders completely and reinstall the module using VSCode and it worked. Thank you very much for your help! :D

**Comment by ritwickdey** [comment]
Thanks for the confirmation! 

If you really like the extension, please drop a review in vscode marketplace.
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
